name: {{ cookiecutter.project_slug }}
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- invoke
- jupyter
- jupyterlab
- matplotlib
- numpy
- pandas
- pandas-profiling
- path.py
- python=3
- scikit-learn
- seaborn
- statsmodels
- pip:
  - h2o
  - kaggle
  - keras
  - lightgbm
  - nbdime
  - pyspark